import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import VideoPlayer from './video-player'

export default function Home() {

  return (
    <>
      <Head>
        <title>Karaoke App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/microphone.ico" />
      </Head>
      <main className={styles.main}>
        {/* <VideoPlayer /> */}
      </main>
    </>
  )
}
